# Generated by Django 3.2.7 on 2021-09-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateField(),
        ),
    ]
